#!/bin/bash

if [[ "$1" == "dos" ]]; then
sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << FDISK_CMDS  | sudo fdisk /dev/sda
o      # create new GPT partition
n      # add new partition
p
1      # partition number
       # default - first sector 
+512MiB # partition size
n
p      # add new partition
2      # partition number
       # default - first sector 
+1GiB # partition size
n
p      # add new partition
3      # partition number
       # default - first sector 
       # default - last sector 
t      # change partition type
1      # partition number
83      # Linux filesystem
t      # change partition type
2      # partition number
82     # Linux filesystem
t      # change partition type
3      # partition number
83     # Linux filesystem
w      # write partition table and exit
FDISK_CMDS

elif [[ "$1" == "gpt" ]]; then

sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << FDISK_CMDS  | sudo fdisk /dev/sda
g      # create new GPT partition
n      # add new partition
1      # partition number
       # default - first sector 
+512MiB # partition size
n      # add new partition
2      # partition number
       # default - first sector 
+1GiB # partition size
n      # add new partition
3      # partition number
       # default - first sector 
       # default - last sector 
t      # change partition type
1      # partition number
1      # Linux filesystem
t      # change partition type
2      # partition number
19     # Linux filesystem
t      # change partition type
3      # partition number
20     # Linux filesystem
w      # write partition table and exit
FDISK_CMDS

fi
