#!/bin/bash

sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << FDISK_CMDS  | sudo fdisk /dev/sdc
g      # create new GPT partition
n      # add new partition
1      # partition number
       # default - first sector 
+64MiB # partition size
n      # add new partition
2      # partition number
       # default - first sector 
       # default - last sector 
t      # change partition type
1      # partition number
83     # Linux filesystem
t      # change partition type
2      # partition number
83     # Linux filesystem
w      # write partition table and exit
FDISK_CMDS
